name: go-todolist

services:
  db:
    image: postgres:16-alpine
    container_name: pg-todolist
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todolist_db
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: devops
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-todolist
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  pg_data:
